### ISSUE TITLE
Error in using the package

### ISSUE THREAD

**Issue by debsush** [leeper/imguR#6]
Hi,

I am using your package for the first time.  I get the following error whenever I try an operation

```
Error in curl::handle_setopt(handle, .list = req$options) : 
  Option httpheader (10023) not supported.
```

Code:

```R
library('imguR')
i <- imgur('pdf') # first argument to `imgur` is any graphics device function
plot(x=1:10, y=-1:-10, col=1:10, pch=19, main="oh hai dere")
imgur_off(i)
```

Was wondering if you could suggest me the way out

Thank you
SD

**Comment by debsush** [comment]
Hi,

Any progress updates

Thank you
SD

**Comment by leeper** [comment]
@debsush This should be fixed now.
