### ISSUE TITLE
post base64 image onto imguR

### ISSUE THREAD

**Issue by debsush** [leeper/imguR#8]
Hi,

I know that we can post native R graphics onto imguR using your package. Now if I have a base64 variable of an image, can I use your package in some way to post it onto imguR.

I am current able to decode the base64 using the base64enc package into a vector if required but cannot save it to a PNG file which would have allowed me to use the upload_image function to load the PNG file.  

What are my options here, if any.  Thank you for your help

SD

**Comment by leeper** [comment]
Once you have an R representation of the image, can't you write the object to a file using, for example, `writeBin()`?

**Comment by debsush** [comment]
Yes, you are right.  Thank you for the wonderful package
